version: "3.9"
services:
  client:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://server:5000
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/EmployeesData
    ports:
      - "5000:5000"
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db

volumes:
  mongo-db-data:
